//COIN LIST
export const REQUEST_COIN_LIST = 'REQUEST_COIN_LIST';
export const RECEIVE_COIN_LIST = 'RECEIVE_COIN_LIST';
export const ERROR_ON_COIN_LIST_FETCH = 'ERROR_ON_COIN_LIST_FETCH';

//QUOTES
export const GET_QUOTES = 'GET_QUOTES';
